### ISSUE TITLE
Worker failed to boot

### ISSUE THREAD

**Issue by liketurbo** [toncenter/ton-http-api#83]
## Environment

  * **OS:** Alpine Linux 3.17.3-x86_64
  * **Docker:** 20.10.21

## What steps will reproduce the problem?

  1. Clone the repository
  2. Configure the environment variables
  3. Run `docker-compose up`

## What is the expected result?

The worker should not throw an error.

## What happens instead?

The worker fails to boot and the error is thrown:
```
main_1  | [2023-03-31 15:02:00 +0000] [8] [ERROR] Traceback (most recent call last):
main_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 677, in lifespan
main_1  |     async with self.lifespan_context(app) as maybe_state:
main_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 566, in __aenter__
main_1  |     await self._router.startup()
main_1  |   File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 654, in startup
main_1  |     await handler()
main_1  |   File "/app/pyTON/main.py", line 127, in startup
main_1  |     tonlib = TonlibManager(tonlib_settings=settings.tonlib,
main_1  |   File "/app/pyTON/manager.py", line 44, in __init__
main_1  |     self.threadpool_executor = ThreadPoolExecutor(max_workers=max(32, len(self.tonlib_settings.liteserver_config['liteservers']) * 4))
main_1  |   File "/app/pyTON/settings.py", line 34, in liteserver_config
main_1  |     self._liteserver_config = json.load(f)
main_1  |   File "/usr/lib/python3.8/json/__init__.py", line 293, in load
main_1  |     return loads(fp.read(),
main_1  |   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
main_1  |     return _default_decoder.decode(s)
main_1  |   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
main_1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
main_1  |   File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
main_1  |     obj, end = self.scan_once(s, idx)
main_1  | json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 125 column 9 (char 3722)
main_1  |
main_1  | [2023-03-31 15:02:00 +0000] [8] [ERROR] Application startup failed. Exiting.
main_1  | [2023-03-31 15:02:00 +0000] [8] [INFO] Worker exiting (pid: 8)
main_1  | [2023-03-31 15:02:01 +0000] [1] [INFO] Shutting down: Master
main_1  | [2023-03-31 15:02:01 +0000] [1] [INFO] Reason: Worker failed to boot.
```

**Comment by kdimentionaltree** [comment]
Hello, this problem should be fixed in v2.0.63. Please reopen the issue if it's still relevant.
